export const DEFAULT_NOISE_REPORT_AUTO_CLOSE_MINUTES = 10;
export const MIN_NOISE_REPORT_AUTO_CLOSE_MINUTES = 1;
export const MAX_NOISE_REPORT_AUTO_CLOSE_MINUTES = 60;

export const DEFAULT_NOISE_REPORT_RETENTION_DAYS = 14;
export const MIN_NOISE_REPORT_RETENTION_DAYS = 1;
export const MAX_NOISE_REPORT_RETENTION_DAYS_FALLBACK = 365;
