import {
  AlignHorizontalSpaceAround,
  ArchiveRestore,
  ArrowDown,
  ArrowUp,
  ArrowUpDown,
  BarChart3,
  Bell,
  BellRing,
  Blend,
  BookOpen,
  Brush,
  Bug,
  CalendarClock,
  CalendarDays,
  ChartNoAxesCombined,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronUp,
  CircleAlert,
  CircleHelp,
  Clock3,
  ClockArrowUp,
  Cloud,
  CloudFog,
  CloudLightning,
  CloudMoon,
  CloudRain,
  CloudSnow,
  CloudSun,
  Code2,
  Command,
  Copy,
  Database,
  Delete,
  Download,
  Droplets,
  Eraser,
  Eye,
  File,
  FileSpreadsheet,
  FileText,
  Gauge,
  Globe,
  GripVertical,
  HardDrive,
  History,
  Image,
  Info,
  Layers,
  MapPin,
  Maximize2,
  MessageSquareText,
  Mic2,
  Minimize2,
  Minus,
  MonitorCheck,
  Moon,
  Palette,
  PartyPopper,
  Pause,
  Pencil,
  Play,
  Plus,
  RadioTower,
  RefreshCw,
  RotateCcw,
  RotateCw,
  Scale,
  ScanLine,
  Search,
  Server,
  Settings,
  ShieldAlert,
  SlidersHorizontal,
  SquareRoundCorner,
  Sun,
  Sunrise,
  Tag,
  Thermometer,
  Timer,
  TimerReset,
  Trash2,
  TriangleAlert,
  Type,
  Upload,
  UserRound,
  Volume2,
  WandSparkles,
  Waves,
  Wind,
  X,
  type LucideIcon,
} from "lucide-react";

export const appIconRegistry = {
  "action.add": Plus,
  "action.apply": Check,
  "action.calibrateMicrophone": Mic2,
  "action.close": X,
  "action.collapse": ChevronUp,
  "action.configure": Settings,
  "action.copy": Copy,
  "action.clearCalibration": Eraser,
  "action.decrement": Minus,
  "action.delete": Trash2,
  "action.download": Download,
  "action.drag": GripVertical,
  "action.edit": Pencil,
  "action.expand": ChevronDown,
  "action.increment": Plus,
  "action.maximize": Maximize2,
  "action.minimize": Minimize2,
  "action.moveDown": ArrowDown,
  "action.moveUp": ArrowUp,
  "action.pause": Pause,
  "action.play": Play,
  "action.refresh": RefreshCw,
  "action.reset": RotateCcw,
  "action.restart": RotateCw,
  "action.restoreSaved": ArchiveRestore,
  "action.search": Search,
  "action.sort": ArrowUpDown,
  "action.upload": Upload,
  "appearance.applyTo": Brush,
  "appearance.background": Image,
  "appearance.blur": Blend,
  "appearance.border": ScanLine,
  "appearance.color": Palette,
  "appearance.effects": WandSparkles,
  "appearance.font": Type,
  "appearance.letterSpacing": AlignHorizontalSpaceAround,
  "appearance.preview": Eye,
  "appearance.radius": SquareRoundCorner,
  "appearance.shadow": Layers,
  "feature.about": Info,
  "feature.announcement": Bell,
  "feature.appearance": Palette,
  "feature.audio": Volume2,
  "feature.authorWebsite": Globe,
  "feature.backup": HardDrive,
  "feature.backspace": Delete,
  "feature.changelog": FileText,
  "feature.command": Command,
  "feature.countdown": TimerReset,
  "feature.carousel": RotateCw,
  "feature.data": Database,
  "feature.diagnostics": Bug,
  "feature.event": CalendarClock,
  "feature.eventName": Tag,
  "feature.feedback": MessageSquareText,
  "feature.date": CalendarDays,
  "feature.file": File,
  "feature.keepAwake": MonitorCheck,
  "feature.license": Scale,
  "feature.location": MapPin,
  "feature.localContent": File,
  "feature.microphone": Mic2,
  "feature.message": MessageSquareText,
  "feature.noise": Gauge,
  "feature.noiseHistory": History,
  "feature.noiseSmoothing": Waves,
  "feature.noiseReport": ChartNoAxesCombined,
  "feature.notification": BellRing,
  "feature.privacy": ShieldAlert,
  "feature.progress": Clock3,
  "feature.quotes": BookOpen,
  "feature.remoteContent": Cloud,
  "feature.schedule": FileSpreadsheet,
  "feature.settings": SlidersHorizontal,
  "feature.sourceCode": Code2,
  "feature.study": BookOpen,
  "feature.studyMetrics": BarChart3,
  "feature.studyThreshold": Gauge,
  "feature.storage": HardDrive,
  "feature.sync": RefreshCw,
  "feature.time": Clock3,
  "feature.typingSpeed": Gauge,
  "feature.userData": UserRound,
  "feature.timeCalibration": ClockArrowUp,
  "feature.timeSourceApi": Server,
  "feature.timeSourceHttp": Globe,
  "feature.timeSourceNtp": RadioTower,
  "feature.weather": CloudSun,
  "feature.weatherAlerts": BellRing,
  "feature.weatherLive": CloudSun,
  "feature.weatherPrecipitation": CloudRain,
  "feature.weatherSunrise": Sunrise,
  "feature.weatherWind": Wind,
  "feature.workspace": SlidersHorizontal,
  "mode.clock": Clock3,
  "mode.countdown": Timer,
  "mode.stopwatch": TimerReset,
  "mode.study": BookOpen,
  "status.error": CircleAlert,
  "status.help": CircleHelp,
  "status.info": Info,
  "status.loading": RefreshCw,
  "status.milestone": PartyPopper,
  "status.selected": Check,
  "status.success": CheckCircle2,
  "status.warning": TriangleAlert,
  "weather.airQuality": Wind,
  "weather.clearDay": Sun,
  "weather.clearNight": Moon,
  "weather.cloudy": Cloud,
  "weather.fog": CloudFog,
  "weather.humidity": Droplets,
  "weather.partlyCloudyDay": CloudSun,
  "weather.partlyCloudyNight": CloudMoon,
  "weather.pressure": Gauge,
  "weather.rain": CloudRain,
  "weather.snow": CloudSnow,
  "weather.sunrise": Sunrise,
  "weather.temperature": Thermometer,
  "weather.thunderstorm": CloudLightning,
  "weather.windDirection": ArrowUp,
  "weather.wind": Wind,
} as const satisfies Record<string, LucideIcon>;

export type AppIconName = keyof typeof appIconRegistry;

export const APP_ICON_NAMES = Object.freeze(Object.keys(appIconRegistry) as AppIconName[]);
